language: php
env:
  - LIB_DIR="/home/travis/build/kosinix/grafikon/"
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  
matrix:
    allow_failures:
      - php: 5.2
      - php: 5.3

branches:
  only:
  - master
  - develop

before_install:
  - apt-cache policy imagemagick
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then printf "\n" | pecl install -f imagick-3.1.2; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then printf "\n" | pecl install -f imagick-3.3.0; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then printf "\n" | pecl install -f imagick-3.4.3; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then printf "\n" | pecl install -f imagick-3.4.3; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then printf "\n" | pecl install -f imagick-3.4.3; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then printf "\n" | pecl install -f imagick-beta; fi

before_script:
  - sudo rm -rf /home/travis/build/kosinix/grafikon/tests/out
  - sudo mkdir -p /home/travis/build/kosinix/grafikon/tests/out
  - sudo chmod -R 0777 /home/travis/build/kosinix/grafikon/tests/
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then phpenv config-rm xdebug.ini; fi


script:
  - php /home/travis/build/kosinix/grafikon/tests/test-gd.php
  - php /home/travis/build/kosinix/grafikon/tests/test-imagick.php