language: php
env:
  - LIB_DIR="/home/travis/build/kosinix/grafikon/"
php:
  - 5.2
  
matrix:
    allow_failures:
      - php: 5.2

branches:
  only:
  - master
  - develop

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.2" ]]; then printf "\n" | pecl install -f imagick-3.1.2; fi

before_script:
  - sudo mkdir -p /home/travis/build/kosinix/grafikon/tests/out
  - sudo chmod -R 0777 /home/travis/build/kosinix/grafikon/tests/
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then phpenv config-rm xdebug.ini; fi


script:
  - php /home/travis/build/kosinix/grafikon/tests/test-gd.php
  - php /home/travis/build/kosinix/grafikon/tests/test-imagick.php